
package fr.adaming.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service.adaming.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToFranc", targetNamespace = "http://service.adaming.fr/", className = "fr.adaming.service.ConversionEuroToFranc")
    @ResponseWrapper(localName = "conversionEuroToFrancResponse", targetNamespace = "http://service.adaming.fr/", className = "fr.adaming.service.ConversionEuroToFrancResponse")
    @Action(input = "http://service.adaming.fr/BanqueWS/conversionEuroToFrancRequest", output = "http://service.adaming.fr/BanqueWS/conversionEuroToFrancResponse")
    public double conversionEuroToFranc(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param idCompte
     * @return
     *     returns fr.adaming.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service.adaming.fr/", className = "fr.adaming.service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service.adaming.fr/", className = "fr.adaming.service.GetCompteResponse")
    @Action(input = "http://service.adaming.fr/BanqueWS/getCompteRequest", output = "http://service.adaming.fr/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "idCompte", targetNamespace = "")
        long idCompte);

    /**
     * 
     * @return
     *     returns java.util.List<fr.adaming.service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service.adaming.fr/", className = "fr.adaming.service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service.adaming.fr/", className = "fr.adaming.service.GetComptesResponse")
    @Action(input = "http://service.adaming.fr/BanqueWS/getComptesRequest", output = "http://service.adaming.fr/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

}
